# File: my_moveit_config/config/pilz_planning_pipeline.yaml

planning_pipelines:
  pilz_industrial_motion_planner:
    planning_plugin: pilz_industrial_motion_planner/PilzIndustrialMotionPlanner
    request_adapters:
      - default_planning_request_adapters/ResolveConstraintFrames
      - default_planning_request_adapters/FixWorkspaceBounds
      - default_planning_request_adapters/FixStartStateBounds
      - default_planning_request_adapters/FixStartStateCollision
      - default_planning_request_adapters/FixStartStatePathConstraints