servo_node:
  ros__parameters:
    move_group_name: arm
    planning_frame: base_link
    ee_frame_name: tool0
    robot_link_command_frame: base_link

    command_out_type: trajectory_msgs/JointTrajectory
    command_out_topic: /scaled_joint_trajectory_controller/joint_trajectory

    publish_period: 0.002
    num_outgoing_halt_msgs_to_publish: 4

    linear_scale: 0.5
    rotational_scale: 0.5

    robot_description: robot_description
    robot_description_semantic: robot_description_semantic

    publish_joint_positions: true
    publish_joint_velocities: true
    publish_joint_accelerations: false

    check_collisions: true
    collision_check_rate: 10.0

    incoming_twist_command_topic: /servo_node/delta_twist_cmds
    incoming_joint_command_topic: /servo_node/delta_joint_cmds
