moveit_servo:
  ros__parameters:
    ## --- REQUIRED PARAMETERS ---
    planning_group_name: "arm"              
    move_group_name: "arm"           # Must match SRDF planning group name
    command_out_type: trajectory_msgs/msg/JointTrajectory
    command_out_topic: /joint_trajectory_controller/joint_trajectory

    # If publishing PoseStamped or TwistStamped for Cartesian servoing:
    cartesian_command_in_topic: /target_pose           # Matches your node's publisher
    link_name_for_cartesian_command: tool0             # Must match your URDF's end-effector link

    ## --- GENERAL SERVO PARAMETERS ---
    use_gazebo: true                                   # True when using Gazebo simulation
    publish_period: 0.02                               # 50 Hz (should match your publisher)
    low_pass_filter_coeff: 2.0                         # 1.0–5.0 typical (higher = smoother but more delay)

    ## --- IK SOLVER PARAMETERS ---
    # Name must match what MoveIt is configured with in kinematics.yaml
    inverse_kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

    ## --- SCALE FACTORS ---
    # Reduce speeds while tuning — you can set closer to 1.0 after testing on hardware
    linear_scale: 0.3                                  # 30% of max linear speed
    rotational_scale: 0.3                              # 30% of max rotational speed

    ## --- JOINT-SPACE PARAMETERS ---
    joint_limit_margin: 0.1                            # rad margin from joint limits (avoid limit hits)

    ## --- COLLISION CHECKING ---
    check_collisions: true                             # Enable collision checking in servo loop
    collision_check_rate: 10.0                         # Hz; increase to 50Hz for safety-critical tasks

    ## --- SINGULARITY HANDLING & STOPPING ---
    # Thresholds are in condition number of Jacobian; lower = more conservative
    lower_singularity_threshold: 20.0                  # Warn & slow near singularity
    hard_stop_singularity_threshold: 35.0              # Stop completely if exceeded

    ## --- JOINT STATE HANDLING ---
    incoming_command_timeout: 0.1                      # Stop if no command for 0.1s (safety)

    ## --- DEBUG/LOGGING ---
    status_topic_name: /servo_status                   # Publishes status messages
    publish_joint_positions: true                      # Good for debugging in RViz
    publish_joint_velocities: false
    publish_joint_accelerations: false
